MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('2')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 12]
  SIE_CAMERA: False
  SIE_VIEW: False
  SIE_COE: 3.0
  JPM: False
  SHIFT_NUM: 8
  RE_ARRANGE: True
  Topk: 0.1


INPUT:
  SIZE_TRAIN: [224, 212]
  SIZE_TEST: [224, 212]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('veri')
  ROOT_DIR: ('../Data_VeReID')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 200
  BASE_LR: 0.045
  IMS_PER_BATCH: 128
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 5
  EVAL_PERIOD: 5
  WEIGHT_DECAY:  1e-5
  WEIGHT_DECAY_BIAS: 1e-5
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './save_weights/veri_vit_transreid_224x212_random_shuffle_75_25'

